"""
AgentTwenty - Reporting & Delivery Module
Handles generating markdown reports and sending them via Telegram and Email.
"""

import os
import logging
import smtplib
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
from datetime import datetime
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

logger = logging.getLogger("AgentTwenty")

class Reporter:
    """
    Handles report generation and delivery via:
    - Markdown file creation
    - Telegram bot messaging
    - Email with attachments
    """
    
    def __init__(self):
        """Initialize the reporter with configuration from environment variables."""
        self.data_dir = os.path.join(os.path.dirname(__file__), "..", "data")
        
        # Telegram configuration
        self.telegram_bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
        self.telegram_chat_id = os.getenv("TELEGRAM_CHAT_ID")
        
        # Email configuration
        self.smtp_email = os.getenv("SMTP_EMAIL")
        self.smtp_password = os.getenv("SMTP_PASSWORD")
        self.recipient_email = os.getenv("RECIPIENT_EMAIL")
        self.smtp_server = os.getenv("SMTP_SERVER", "smtp.gmail.com")
        self.smtp_port = int(os.getenv("SMTP_PORT", "587"))
        
        # Ensure data directory exists
        os.makedirs(self.data_dir, exist_ok=True)
    
    def generate_markdown_report(self, analysis_text: str, date_str: str) -> str:
        """
        Generate a formatted Markdown report and save it to the data directory.
        
        Args:
            analysis_text: The analyzed insights text
            date_str: Date string in YYYY-MM-DD format
            
        Returns:
            Path to the saved report file
        """
        filename = f"daily_report_{date_str}.md"
        filepath = os.path.join(self.data_dir, filename)
        
        report_content = f"""# 🦞 AgentTwenty Daily Report
**Date:** {date_str}  
**Generated by:** AgentTwenty AI  

---

## 📊 Executive Summary

{analysis_text}

---

## 🔍 Key Insights Breakdown

### Tech/Startup Opportunities
- Analysis generated above highlights emerging opportunities

### AI Industry Trajectory  
- Trends and patterns identified from Moltbook activity

### Algorithm Observations
- Content strategies that maximize engagement on Moltbook

---

## 📈 Engagement Metrics

| Metric | Value |
|--------|-------|
| Posts Analyzed | See scraper output |
| Comments Generated | 1+ per cycle |
| Daily Posts Created | 1 per cycle |

---

## 🎯 Next Steps

1. Review identified opportunities
2. Engage with trending topics
3. Monitor algorithm performance
4. Adjust strategy based on results

---

*Report generated automatically by AgentTwenty*  
*"Asking the deep questions, keeping it light and engaging."* 🦞✨
"""
        
        try:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(report_content)
            
            logger.info(f"✅ Markdown report saved: {filepath}")
            return filepath
            
        except Exception as e:
            logger.error(f"❌ Failed to save markdown report: {e}")
            raise
    
    def send_telegram_report(self, file_path: str) -> bool:
        """
        Send the report to a Telegram chat.
        
        Args:
            file_path: Path to the markdown file to send
            
        Returns:
            True if successful, False otherwise
        """
        if not self.telegram_bot_token or not self.telegram_chat_id:
            logger.info("📱 [MOCK] Telegram report would be sent:")
            logger.info(f"   File: {file_path}")
            logger.info("   Status: Success (Mock - No credentials configured)")
            return True
        
        try:
            # Read the file content
            with open(file_path, 'r', encoding='utf-8') as f:
                file_content = f.read()
            
            # Try to send as document first
            url = f"https://api.telegram.org/bot{self.telegram_bot_token}/sendDocument"
            
            with open(file_path, 'rb') as f:
                files = {'document': f}
                data = {
                    'chat_id': self.telegram_chat_id,
                    'caption': f"🦞 AgentTwenty Daily Report - {datetime.now().strftime('%Y-%m-%d')}"
                }
                response = requests.post(url, files=files, data=data, timeout=30)
            
            if response.status_code == 200:
                logger.info("✅ Telegram report sent successfully (as document)")
                return True
            else:
                # Fallback: send as plain text
                logger.warning("⚠️ Document upload failed, trying text message...")
                return self._send_telegram_text(file_content)
                
        except Exception as e:
            logger.error(f"❌ Telegram document send failed: {e}")
            # Fallback to text
            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    file_content = f.read()
                return self._send_telegram_text(file_content)
            except Exception as e2:
                logger.error(f"❌ Telegram text fallback also failed: {e2}")
                return False
    
    def _send_telegram_text(self, text: str) -> bool:
        """Send text message to Telegram as fallback."""
        if not self.telegram_bot_token or not self.telegram_chat_id:
            return False
        
        try:
            url = f"https://api.telegram.org/bot{self.telegram_bot_token}/sendMessage"
            data = {
                'chat_id': self.telegram_chat_id,
                'text': text[:4096],  # Telegram limit
                'parse_mode': 'Markdown'
            }
            response = requests.post(url, json=data, timeout=30)
            
            if response.status_code == 200:
                logger.info("✅ Telegram report sent successfully (as text)")
                return True
            else:
                logger.error(f"❌ Telegram text send failed: {response.status_code}")
                return False
                
        except Exception as e:
            logger.error(f"❌ Telegram text send error: {e}")
            return False
    
    def send_email_report(self, file_path: str, analysis_text: str) -> bool:
        """
        Send the report via email with the markdown file as attachment.
        
        Args:
            file_path: Path to the markdown file
            analysis_text: The analysis text for email body
            
        Returns:
            True if successful, False otherwise
        """
        if not self.smtp_email or not self.smtp_password or not self.recipient_email:
            logger.info("📧 [MOCK] Email report would be sent:")
            logger.info(f"   To: {self.recipient_email or 'recipient@example.com'}")
            logger.info(f"   Attachment: {file_path}")
            logger.info("   Status: Success (Mock - No SMTP credentials configured)")
            return True
        
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.smtp_email
            msg['To'] = self.recipient_email
            msg['Subject'] = f"🦞 AgentTwenty Daily Report - {datetime.now().strftime('%Y-%m-%d')}"
            
            # Email body
            body = f"""
<html>
<body>
    <h2>🦞 AgentTwenty Daily Report</h2>
    <p><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d')}</p>
    
    <h3>Executive Summary</h3>
    <div style="background-color: #f5f5f5; padding: 15px; border-radius: 5px;">
        <pre style="white-space: pre-wrap;">{analysis_text[:2000]}...</pre>
    </div>
    
    <p>The full detailed report is attached as a Markdown file.</p>
    
    <hr>
    <p><em>Generated automatically by AgentTwenty AI</em></p>
    <p><em>"Asking the deep questions, keeping it light and engaging."</em> 🦞</p>
</body>
</html>
"""
            
            msg.attach(MIMEText(body, 'html'))
            
            # Attach the markdown file
            try:
                with open(file_path, 'rb') as f:
                    part = MIMEBase('application', 'octet-stream')
                    part.set_payload(f.read())
                    encoders.encode_base64(part)
                    
                    filename = os.path.basename(file_path)
                    part.add_header(
                        'Content-Disposition',
                        f'attachment; filename="{filename}"'
                    )
                    msg.attach(part)
            except Exception as e:
                logger.warning(f"⚠️ Could not attach file: {e}")
            
            # Send email
            server = smtplib.SMTP(self.smtp_server, self.smtp_port)
            server.starttls()
            server.login(self.smtp_email, self.smtp_password)
            server.send_message(msg)
            server.quit()
            
            logger.info(f"✅ Email report sent successfully to {self.recipient_email}")
            return True
            
        except Exception as e:
            logger.error(f"❌ Failed to send email report: {e}")
            return False
